name: CI/CD Simple Hello World App

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Detect Changes
        id: changes
        run: |
          git diff --name-only > changed_files.txt
          if grep -q '^frontend/' changed_files.txt; then echo "frontend=true" >> $GITHUB_ENV; fi
          if grep -q '^backend/' changed_files.txt; then echo "backend=true" >> $GITHUB_ENV; fi
          echo ${{ env.frontend }}


      - name: Build & Push Frontend Container
        if: ${{ env.frontend == 'true' }}
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-frontend:latest

      - name: Build Backend Container
        if: ${{ env.backend == 'true' }}
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-backend:latest

      - name: Deploy Frontend Container
        if: ${{ env.frontend == 'true' }}
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/node-frontend:latest
            docker stop node-backend || true
            docker rm node-backend || true
            docker run -d --name node-backend -p 8010:4502 ${{ secrets.DOCKER_USERNAME }}/node-frontend:latest
          EOF

      - name: Deploy Backend Container
        if: ${{ env.backend == 'true' }}
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/node-backend:latest
            docker stop node-backend || true
            docker rm node-backend || true
            docker run -d --name node-backend -p 8020:4501 ${{ secrets.DOCKER_USERNAME }}/node-backend:latest
          EOF
